### ISSUE TITLE
Project compiles with 1.8 but throws an exception at runtime

### ISSUE THREAD

**Issue by hrzafer** [ahmetaa/zemberek-nlp#28]
I have Apache Solr plugin project with the following dependency:

 <dependency>
          <groupId>zemberek-nlp</groupId>
          <artifactId>core</artifactId>
          <version>0.9.0</version>
</dependency>

On Intellij selecting both 1.7 and 1.8 works with no problem. However with Solr for JDK 1.8,
it throws the following exception:

Note: Solr also works on the same 1.8 JVM

```
"trace": "java.lang.RuntimeException: java.lang.NoClassDefFoundError: zemberek/core/DoubleValueSet\r\n\tat org.apache.solr.servlet.SolrDispatchFilter.sendError(SolrDispatchFilter.java:724)\r\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:434)\r\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:197)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\r\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\r\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)\r\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)\r\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\r\n\tat org.eclipse.jetty.server.Server.handle(Server.java:368)\r\n\tat org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)\r\n\tat org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)\r\n\tat org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)\r\n\tat org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)\r\n\tat org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)\r\n\tat org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)\r\n\tat org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)\r\n\tat org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)\r\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)\r\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)\r\n\tat java.lang.Thread.run(Unknown Source)\r\nCaused by: java.lang.NoClassDefFoundError: zemberek/core/DoubleValueSet\r\n\tat tr.gov.bilgem.damla.solr.plugin.suggesters.SingleWordSpellChecker.decode(SingleWordSpellChecker.java:330)\r\n\tat tr.gov.bilgem.damla.solr.plugin.suggesters.DamlaSuggester.spellcheck(DamlaSuggester.java:279)\r\n\tat tr.gov.bilgem.damla.solr.plugin.suggesters.DamlaSuggester.correctToken(DamlaSuggester.java:299)\r\n\tat tr.gov.bilgem.damla.solr.plugin.suggesters.DamlaSuggester.getSuggestions(DamlaSuggester.java:196)\r\n\tat org.apache.solr.handler.component.SpellCheckComponent.process(SpellCheckComponent.java:189)\r\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:208)\r\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)\r\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:1859)\r\n\tat org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:710)\r\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:413)\r\n\t... 26 more\r\n",
```

**Comment by asimokby** [comment]
Hey! I am still getting this error. What do you mean you found a problem with your maven command? How did you solve that problem? @hrzafer
